server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/postgres}
#    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db.migration.v1/changelog.yaml
  jpa:
    open-in-view: on
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
